const challenges=[
{id:1,name:"Monthly Sales Dashboard",track:"Data Analytics",difficulty:"Beginner",description:"Clean a monthly sales dataset and build a dashboard showing key trends.",outcome:"A simple dashboard showing important sales insights.",objective:"Turn raw sales records into a clear business summary.",skills:"Spreadsheets, data cleaning, charts.",tools:"Google Sheets or Excel.",deliverable:"Cleaned dataset plus a summary dashboard.",time:"3–4 hours"},
{id:2,name:"Customer Churn Snapshot",track:"Data Analytics",difficulty:"Intermediate",description:"Use customer data to identify segments that may be at risk of leaving.",outcome:"A short findings report backed by numbers.",objective:"Answer a focused business question through filtering and segmentation.",skills:"Pivot tables, filtering, basic SQL.",tools:"Spreadsheets or SQL playground.",deliverable:"One-page findings summary.",time:"4–5 hours"},
{id:3,name:"Employee Data Cleanup & Insights",track:"Data Analytics",difficulty:"Beginner",description:"Clean an employee dataset and answer three workforce questions.",outcome:"A clean dataset with supporting insights.",objective:"Practice duplicates, blanks, inconsistent formatting and aggregation.",skills:"Data cleaning, formulas, aggregation.",tools:"Google Sheets or Excel.",deliverable:"Cleaned spreadsheet and notes.",time:"3 hours"},
{id:4,name:"Personal Portfolio Landing Page",track:"Web Development",difficulty:"Beginner",description:"Design and build a responsive one-page portfolio introducing yourself and your work.",outcome:"A publish-ready landing page.",objective:"Practice semantic HTML, CSS layout and responsive design.",skills:"HTML, CSS, responsive layout.",tools:"Code editor and browser.",deliverable:"Deployed index.html and style.css.",time:"3–4 hours"},
{id:5,name:"Contact Form UI",track:"Web Development",difficulty:"Beginner",description:"Build an accessible contact form with clear validation states.",outcome:"A polished front-end form.",objective:"Practice forms, labels, validation and interaction.",skills:"HTML forms, CSS, JavaScript.",tools:"Code editor and browser.",deliverable:"A single responsive form page.",time:"3 hours"},
{id:6,name:"Interactive Pricing Page",track:"Web Development",difficulty:"Advanced",description:"Build a pricing page with monthly/yearly toggles and instant price updates.",outcome:"A polished interactive pricing component.",objective:"Practice DOM manipulation and event-driven UI updates.",skills:"JavaScript, DOM, CSS layout.",tools:"Code editor and browser.",deliverable:"HTML/CSS/JS pricing page.",time:"4–5 hours"}];
let activeTrack="All",activeDifficulty="All";
const grid=document.getElementById("challengeGrid"),empty=document.getElementById("emptyState"),count=document.getElementById("challengeCount"),search=document.getElementById("challengeSearch"),overlay=document.getElementById("modalOverlay"),modal=document.getElementById("modalContent");
function renderCard(c){return `<article class="card"><div class="tag-row"><span class="program-tag">${c.track}</span><span class="pill ${c.difficulty==="Beginner"?"pill-completed":c.difficulty==="Intermediate"?"pill-progress":"pill-not-started"}">${c.difficulty}</span></div><h3>${c.name}</h3><p>${c.description}</p><p><strong>Expected outcome:</strong> ${c.outcome}</p><button class="btn btn-outline btn-sm" data-view="${c.id}">View Challenge →</button></article>`}
function applyFilters(){const q=search.value.trim().toLowerCase();const list=challenges.filter(c=>(activeTrack==="All"||c.track===activeTrack)&&(activeDifficulty==="All"||c.difficulty===activeDifficulty)&&(!q||[c.name,c.track,c.description,c.outcome,c.skills].join(" ").toLowerCase().includes(q)));count.textContent=`${list.length} challenge${list.length===1?"":"s"}`;grid.innerHTML=list.map(renderCard).join("");empty.style.display=list.length?"none":"block";document.querySelectorAll("[data-view]").forEach(b=>b.addEventListener("click",()=>openModal(Number(b.dataset.view))))}
function openModal(id){const c=challenges.find(x=>x.id===id);if(!c)return;modal.innerHTML=`<div class="eyebrow">${c.track} · ${c.difficulty}</div><h2>${c.name}</h2><p>${c.description}</p><div class="card" style="padding:18px;margin:18px 0"><p><strong>Objective</strong><br>${c.objective}</p><p><strong>Skills</strong><br>${c.skills}</p><p><strong>Tools</strong><br>${c.tools}</p><p><strong>Deliverable</strong><br>${c.deliverable}</p><p style="margin:0"><strong>Estimated time</strong><br>${c.time}</p></div><p style="margin:0"><strong>Expected outcome:</strong> ${c.outcome}</p>`;overlay.classList.add("open")}
document.getElementById("trackFilters").addEventListener("click",e=>{const b=e.target.closest(".filter-btn");if(!b)return;activeTrack=b.dataset.track;document.querySelectorAll("#trackFilters .filter-btn").forEach(x=>x.classList.toggle("active",x===b));applyFilters()});
document.getElementById("difficultyFilters").addEventListener("click",e=>{const b=e.target.closest(".filter-btn");if(!b)return;activeDifficulty=b.dataset.difficulty;document.querySelectorAll("#difficultyFilters .filter-btn").forEach(x=>x.classList.toggle("active",x===b));applyFilters()});
search.addEventListener("input",applyFilters);document.getElementById("modalClose").addEventListener("click",()=>overlay.classList.remove("open"));overlay.addEventListener("click",e=>{if(e.target===overlay)overlay.classList.remove("open")});document.addEventListener("keydown",e=>{if(e.key==="Escape")overlay.classList.remove("open")});applyFilters();