const API_BASE="";
let tasks=[],activeStatusFilter="all";
const challenges=[
{name:"Monthly Sales Dashboard",track:"Data Analytics",difficulty:"Beginner",description:"Clean a monthly sales dataset and build a dashboard showing key trends."},
{name:"Customer Churn Snapshot",track:"Data Analytics",difficulty:"Intermediate",description:"Use customer data to identify segments that may be at risk of leaving."},
{name:"Employee Data Cleanup & Insights",track:"Data Analytics",difficulty:"Beginner",description:"Clean an employee dataset and answer three workforce questions."},
{name:"Personal Portfolio Landing Page",track:"Web Development",difficulty:"Beginner",description:"Design and build a responsive one-page portfolio."},
{name:"Contact Form UI",track:"Web Development",difficulty:"Beginner",description:"Build an accessible contact form with clear validation states."},
{name:"Interactive Pricing Page",track:"Web Development",difficulty:"Advanced",description:"Build a pricing page with monthly/yearly toggles and instant price updates."}];
const taskGrid=document.getElementById("taskGrid"),loadingState=document.getElementById("loadingState"),errorState=document.getElementById("errorState"),completedCountEl=document.getElementById("completedCount"),remainingCountEl=document.getElementById("remainingCount"),percentValueEl=document.getElementById("percentValue"),progressFillEl=document.getElementById("progressFill"),statusDot=document.getElementById("statusDot"),statusText=document.getElementById("statusText"),modalOverlay=document.getElementById("modalOverlay"),modalContent=document.getElementById("modalContent"),searchInput=document.getElementById("platformSearch"),searchResults=document.getElementById("searchResults");
async function checkApiStatus(){try{const r=await fetch(API_BASE+"/api/status");if(!r.ok)throw 0;statusDot.className="status-dot status-connected";statusText.textContent="Backend Status: Connected"}catch(e){statusDot.className="status-dot status-offline";statusText.textContent="Backend Status: Offline"}}
async function loadTasks(){loadingState.style.display="block";errorState.style.display="none";taskGrid.innerHTML="";try{const r=await fetch(API_BASE+"/api/tasks");if(!r.ok)throw 0;tasks=await r.json();loadingState.style.display="none";renderTasks();updateProgress();renderSearch()}catch(e){loadingState.style.display="none";errorState.style.display="block";searchResults.innerHTML='<div class="empty-state">Unable to load tasks. Please try again.</div>'}}
function statusLabel(s){return s==="completed"?{text:"Completed",pill:"pill-completed"}:s==="in-progress"?{text:"In Progress",pill:"pill-progress"}:{text:"Not Started",pill:"pill-not-started"}}
function actionButton(t){if(t.status==="completed")return "";return t.status==="in-progress"?`<button class="btn btn-primary btn-sm" data-status-update="${t.id}" data-next-status="completed">Mark Complete</button>`:`<button class="btn btn-primary btn-sm" data-status-update="${t.id}" data-next-status="in-progress">Start Task</button>`}
function renderTaskCard(t){const s=statusLabel(t.status);return `<article class="card task-card"><div class="task-card-top"><div><div class="mono" style="font-size:.65rem;color:var(--muted)">TASK ${t.id} · DAY ${t.day}</div><h3>${t.title}</h3></div><span class="pill ${s.pill}">${s.text}</span></div><p>${t.description}</p><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn btn-outline btn-sm" data-view="${t.id}">View Task</button>${actionButton(t)}</div></article>`}
function renderTasks(){const list=activeStatusFilter==="all"?tasks:tasks.filter(t=>t.status===activeStatusFilter);taskGrid.innerHTML=list.length?list.map(renderTaskCard).join(""):'<div class="empty-state">No tasks match this filter.</div>';document.querySelectorAll("[data-view]").forEach(b=>b.addEventListener("click",()=>viewTask(+b.dataset.view)));document.querySelectorAll("[data-status-update]").forEach(b=>b.addEventListener("click",()=>updateStatus(+b.dataset.statusUpdate,b.dataset.nextStatus)))}
function updateProgress(){const total=tasks.length||8,done=tasks.filter(t=>t.status==="completed").length;completedCountEl.textContent=`${done} / ${total}`;remainingCountEl.textContent=total-done;const pct=Math.round(done/total*100);percentValueEl.textContent=pct+"%";progressFillEl.style.width=pct+"%"}
async function viewTask(id){modalContent.innerHTML="<p>Loading task details…</p>";modalOverlay.classList.add("open");try{const r=await fetch(API_BASE+"/api/tasks/"+id);if(!r.ok)throw 0;const t=await r.json();const s=statusLabel(t.status);modalContent.innerHTML=`<div class="eyebrow">TASK ${t.id} · DAY ${t.day}</div><h2>${t.title}</h2><span class="pill ${s.pill}">${s.text}</span><p style="margin-top:16px">${t.description}</p>`}catch(e){modalContent.innerHTML="<p>Unable to load this task. Please try again.</p>"}}
async function updateStatus(id,status){try{const r=await fetch(API_BASE+"/api/tasks/"+id,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});if(!r.ok)throw 0;const u=await r.json();const i=tasks.findIndex(t=>t.id===u.id);if(i>-1)tasks[i]=u;renderTasks();updateProgress();renderSearch()}catch(e){alert("Could not update the task. Check the API connection.")}}
function renderSearch(){const q=searchInput.value.trim().toLowerCase();if(!q){searchResults.innerHTML="";return}const taskMatches=tasks.filter(t=>[t.title,t.description,String(t.day)].join(" ").toLowerCase().includes(q));const challengeMatches=challenges.filter(c=>[c.name,c.track,c.difficulty,c.description].join(" ").toLowerCase().includes(q));const total=taskMatches.length+challengeMatches.length;if(!total){searchResults.innerHTML='<div class="empty-state">No matching results found.</div>';return}searchResults.innerHTML=`<div class="grid-2">${taskMatches.map(t=>`<button class="card search-result" data-search-task="${t.id}"><span class="eyebrow">Task ${t.id} · Day ${t.day}</span><strong>${t.title}</strong><small>${t.status}</small></button>`).join("")}${challengeMatches.map(c=>`<a class="card search-result" href="challenges.html"><span class="eyebrow">${c.track} · ${c.difficulty}</span><strong>${c.name}</strong><small>Challenge Hub</small></a>`).join("")}</div>`;document.querySelectorAll("[data-search-task]").forEach(b=>b.addEventListener("click",()=>viewTask(+b.dataset.searchTask)))}
document.getElementById("platformSearch").addEventListener("input",renderSearch);
document.getElementById("statusFilters").addEventListener("click",e=>{const b=e.target.closest(".filter-btn");if(!b)return;activeStatusFilter=b.dataset.status;document.querySelectorAll("#statusFilters .filter-btn").forEach(x=>x.classList.toggle("active",x===b));renderTasks()});
document.getElementById("modalClose").addEventListener("click",()=>modalOverlay.classList.remove("open"));modalOverlay.addEventListener("click",e=>{if(e.target===modalOverlay)modalOverlay.classList.remove("open")});document.addEventListener("keydown",e=>{if(e.key==="Escape")modalOverlay.classList.remove("open")});
const techContent={nextjs:["Next.js","A React framework for production web applications with routing, server rendering and deployment tooling."],vue:["Vue.js","A progressive JavaScript framework for building interfaces with a component-based approach."],angular:["Angular","A full front-end framework commonly used for structured, large-scale applications."],backend:["Backend Development","Server-side logic, APIs and data systems. Technologies can include Node.js/Express, Django, Flask, Laravel and .NET."]};
document.getElementById("techTabs").addEventListener("click",e=>{const b=e.target.closest(".filter-btn");if(!b)return;document.querySelectorAll("#techTabs .filter-btn").forEach(x=>x.classList.toggle("active",x===b));const t=techContent[b.dataset.tech];document.getElementById("techPanel").innerHTML=`<h3>${t[0]}</h3><p style="margin:0">${t[1]}</p>`});
document.getElementById("techPanel").innerHTML=`<h3>${techContent.nextjs[0]}</h3><p style="margin:0">${techContent.nextjs[1]}</p>`;
checkApiStatus();loadTasks();