const webDevTasks=[
{number:1,title:"Build the TechBridge Homepage",day:1,description:"Create the branded TechBridge homepage with programs, internship information and a clear application CTA.",difficulty:"Beginner"},
{number:2,title:"Build the TechBridge Programs Experience",day:4,description:"Present Data Analytics and Web Development, their skills, differentiation and application CTA.",difficulty:"Beginner"},
{number:3,title:"Build the Internship Tasks Experience",day:8,description:"Create an interface that presents all eight internship tasks, days, descriptions and progression.",difficulty:"Beginner → Intermediate"},
{number:4,title:"Build an Interactive Internship Roadmap",day:11,description:"Use JavaScript arrays, objects, functions, event listeners and DOM manipulation to switch tracks without refresh.",difficulty:"Beginner → Intermediate"},
{number:5,title:"Build the TechBridge Challenge Hub",day:15,description:"Create a practical challenge library with track and difficulty filtering, search and detail views.",difficulty:"Intermediate"},
{number:6,title:"Build the Intern Dashboard",day:19,description:"Create a progress dashboard with task status, filters, task details and a technology explorer.",difficulty:"Intermediate"},
{number:7,title:"Build the TechBridge Task Management API",day:22,description:"Build a Node.js/Express REST API and connect the dashboard with fetch(), including task status updates.",difficulty:"Intermediate"},
{number:8,title:"Build the Complete TechBridge Internship Platform",day:26,description:"Bring the homepage, programs, Challenge Hub, dashboard, task management API, search and responsive UI together.",difficulty:"Intermediate"}];
const dataAnalyticsTasks=[
{number:1,title:"Data Cleaning Basics",day:1,description:"Clean a messy dataset in Google Sheets or Excel: duplicates, blanks, formatting and data types.",difficulty:"Beginner"},
{number:2,title:"Formulas & Pivot Tables",day:4,description:"Use spreadsheet formulas and Pivot Tables to extract useful insights.",difficulty:"Beginner"},
{number:3,title:"Data Visualization",day:8,description:"Create charts and a simple dashboard that communicate useful insights.",difficulty:"Beginner → Intermediate"},
{number:4,title:"Introduction to SQL",day:11,description:"Practice basic SQL queries to answer real-world questions about data.",difficulty:"Beginner → Intermediate"},
{number:5,title:"SQL Joins & Aggregations",day:15,description:"Use JOIN, GROUP BY and aggregate functions across related tables.",difficulty:"Intermediate"},
{number:6,title:"Lookup Functions & Data Wrangling",day:19,description:"Use VLOOKUP/XLOOKUP to combine datasets and handle mismatches.",difficulty:"Intermediate"},
{number:7,title:"Mini Analysis Project",day:22,description:"Complete an end-to-end analysis with cleaning, formulas, pivots, charts and recommendations.",difficulty:"Intermediate"},
{number:8,title:"Capstone Project",day:26,description:"Complete a larger project combining spreadsheet analysis and SQL across at least two tables.",difficulty:"Intermediate"}];
const taskListEl=document.getElementById("taskList"),labelEl=document.getElementById("viewingLabel"),summaryEl=document.getElementById("viewingSummary"),buttons=document.querySelectorAll(".track-btn");
function getTrackData(track){return track==="data"?{tasks:dataAnalyticsTasks,label:"Data Analytics",summary:"Clean, query, visualize and explain data through eight progressive stages."}:{tasks:webDevTasks,label:"Web Development",summary:"Build from a branded homepage into a connected internship management platform."}}
function renderTrack(track){const d=getTrackData(track);labelEl.textContent=d.label;summaryEl.textContent=d.summary;buttons.forEach(b=>b.classList.toggle("active",b.dataset.track===track));taskListEl.innerHTML=d.tasks.map(t=>`<article class="roadmap-item"><span class="roadmap-dot"></span><div class="roadmap-day">DAY ${t.day}<br><span class="mono">TASK ${String(t.number).padStart(2,"0")}</span></div><div class="card roadmap-card"><div class="tag-row"><span class="pill pill-completed">STAGE ${t.number}</span><span class="badge-outline">${t.difficulty}</span></div><h3>${t.title}</h3><p>${t.description}</p></div><div></div></article>`).join("")}
buttons.forEach(b=>b.addEventListener("click",()=>renderTrack(b.dataset.track)));renderTrack("webdev");